services:
  mongo_buerno:
    image: mongo:latest
    container_name: mongo_buerno
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: